### ISSUE TITLE
Registering the plugin with TensorRT

### ISSUE THREAD

**Issue by jruizaranguren** [r7vme/tensorrt_l2norm_helper#1]
Hi, I have successfully used your tools to create a tensorrt engine. The problem is that the plugin is not found when loading the engine with:

```
import tensorrt as trt
with open("sample.engine", "rb") as f, trt.Runtime(trt.Logger()) as runtime:
    engine = runtime.deserialize_cuda_engine(f.read())
```

I get the following error:

```
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin L2Norm_Helper_TRT version 1
[TensorRT] ERROR: safeDeserializationUtils.cpp (259) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
```

How should I register the plugin? Thanks.

**Comment by r7vme** [comment]
Hi @jruizaranguren . I'm running inference using c++ api. For python, i believe there should be `pybind` bindings implemented as described in [docs](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#add_custom_layer_python). 

> You can use the C++ API to create a custom layer, package the layer using pybind11 in Python, then load the plugin into a Python application. 

After implementing this, you should compile `.so` with plugin and python bindings and import it.

**Comment by jruizaranguren** [comment]
Thank you. We got it working.

**Comment by elisabetta496** [comment]
> Hi @jruizaranguren . I'm running inference using c++ api. For python, i believe there should be `pybind` bindings implemented as described in [docs](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#add_custom_layer_python).
> 
> > You can use the C++ API to create a custom layer, package the layer using pybind11 in Python, then load the plugin into a Python application.
> 
> After implementing this, you should compile `.so` with plugin and python bindings and import it.

Hi r7vme,
I'm having the same  issue as jruizaranguren. I'm trying to load the engine file with python but the plugin is not found.
Could you help me solving this problem? In which file I have to insert the python  bindings?
Thanks.

**Comment by deaffella** [comment]
> Thank you. We got it working.

hi! did you compiled .so file and connected the plugin to Python?

**Comment by deaffella** [comment]
> Hi @jruizaranguren . I'm running inference using c++ api. For python, i believe there should be `pybind` bindings implemented as described in [docs](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#add_custom_layer_python).
> 
> > You can use the C++ API to create a custom layer, package the layer using pybind11 in Python, then load the plugin into a Python application.
> 
> After implementing this, you should compile `.so` with plugin and python bindings and import it.

Hi! Could you help me with advice on how to create a. so file for the plugin?

**Comment by AnasMK** [comment]
> Thank you. We got it working.

I have come across the same issue, could you please show us the steps to import the plugin to the registry in Python
